### ISSUE TITLE
Override search function ? 

### ISSUE THREAD

**Issue by OmarSherif96** [facuesr/react-multiselect-listbox#2]
Hello,

First of all I am impressed by this component it really helped me through my project , I would highly recommend anyone wants to render big lists without lagging to use it.

My issue : which prop or function should I overwrite to improve search capabilities ? 

Thanks

**Comment by facuesr** [comment]
Hello @OmarSherif96, right now there is not a way to improve search capabilities, but we can add that. Can you share an example of what are you looking for? Thanks.
